reviews:
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - '!**/*.md'
    - '!**/*.txt'
    - '!**/target/**'
    - '!**/node_modules/**'
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
  tools:
    languagetool:
      enabled: true
      level: warn